# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
# *  CLASS input parameter file  *
# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

# Best fit parameters from Planck 2018
# Case 2.17 of:
# https://wiki.cosmos.esa.int/planck-legacy-archive/images/b/be/Baseline_params_table_2018_68pc.pdf
# (but with more significant digits, directly from the chains)

#----------------------------
#----> background parameters:
#----------------------------

H0 = 67.32117
#H0 = 71
omega_b = 0.02238280
N_ur = 2.03066666667
omega_cdm = 0.1201075
N_ncdm = 1
omega_ncdm = 0.0006451439

root = output/test_

frac_dmde = 1.0
g_scf = -0.013
m_scf = 14.3

phi_scf_ini = 0.695

Omega_k = 0

#--------------------------------
#----> thermodynamics parameters:
#--------------------------------

YHe = 0.2454006
tau_reio = 0.05430842

#-------------------------------------
#----> primordial spectrum parameters:
#-------------------------------------

n_s = 0.9660499
A_s = 2.100549e-09

#-----------------------------
#----> non linear corrections:
#-----------------------------

#non linear = halofit

#----------------------------------------
#----> parameters controlling the output:
#----------------------------------------
start_large_k_at_tau_h_over_tau_k=0.01
k_output_values=0.05

output = tCl,pCl,lCl,mPk
#output =
lensing = yes



write warnings = yes
write parameters = yes
write background = yes

input_verbose = 5
background_verbose = 5
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
spectra_verbose = 1
nonlinear_verbose = 1
lensing_verbose = 1
output_verbose = 1
